---
- name: prepare container for test
  hosts: localhost
  gather_facts: no
  connection: local

  tasks:
    - name: Create container centos7
      docker_container:
        name: centos7
        image: hxpro/docker-centos
#        recreate: yes
        privileged: true
        command: /usr/sbin/init
        volumes:
          - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
        state: started

    - name: add centos7 host
      add_host: name=centos7 groups=containers

- name: provision role
  hosts: containers
  connection: docker
  roles:
    - role: "{{ playbook_dir }}"
  tasks:
    - file: path=/var/www/html state=directory
    - copy:
        content='<?php PHPInfo();'
        dest='/var/www/html/index.php'


#- name: tear down
#  hosts: localhost
#  gather_facts: no
#  connection: local
#
#  tasks:
#    - name: Destroy containers
#      docker_container:
#        name: '{{ item }}'
#        state: absent
#      with_items:
#        - centos7
