---
galaxy_info:
  author: "Chris Olstrom"
  categories:
    - system
  description: "Generates SSL certificates"
  license: MIT License
  min_ansible_version: 1.2
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: RedHat
      versions:
        - all
dependencies: []
