---
- name: Install epel-release on CentOS
  yum: name=epel-release state=installed
  when: ansible_distribution == 'CentOS'

- name: Install epel-release on RedHat
  yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm state=installed
  when: ansible_distribution == 'RedHat'
