galaxy_info:
  author: Matěj Koudelka
  description: Nginx

  license: license (WTFPL)

  min_ansible_version: 2.0

  platforms:
    - name: EL
      versions:
        - 7

  galaxy_tags: []

dependencies:
  #- name: hxpro.phpfpm
