---
language: python
python: "2.7"

sudo: true

services:
  - docker

# Install ansible
addons:
  apt:
    packages:
    - python-pip

before_install:
  - docker pull centos:6
  - docker pull centos:7

install:
  # Install ansible
  - sudo pip install ansible
  - sudo pip install docker-py==1.9.0
  - pip list
  - sudo pip list

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # Basic role syntax check
  - cd tests
  - ansible-playbook test.yml --syntax-check
  - ansible-playbook test.yml

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
